---
language: node_js
node_js:
  - "0.10"
before_install:
  - "echo 'installing meteor'"
  - '[ "$(uname -m)" == "i686" -o "$(uname -m)" == "x86_64" ] && mkdir $HOME/.meteor-install-tmp'
  - "curl --fail https://warehouse.meteor.com/bootstrap/0.7.2/meteor-bootstrap-$( uname )_$( uname -m ).tar.gz | tar -xzf - -C $HOME/.meteor-install-tmp"
  - "[[ -d $HOME/.meteor-install-tmp/.meteor/meteor ]] && mv $HOME/.meteor-install-tmp/.meteor $HOME"
  - "test -x $HOME/.meteor/meteor"
  - "echo 'installing meteorite'"
  - "npm install -g meteorite"
  - "echo 'installing runner'"
  - "wget https://raw.github.com/arunoda/travis-ci-meteor-packages/master/Makefile"
  - "wget https://raw.github.com/arunoda/travis-ci-meteor-packages/master/start_test.js"
  - "wget https://raw.github.com/arunoda/travis-ci-meteor-packages/master/phantom_runner.js"
